In [7]:
import os
import time
import pandas_gbq
import pandas as pd

from datetime import datetime
from google.cloud import bigquery

In [3]:
def main(project, query_str):
    """
    This function is the entry point function to fetch the individual files and merge them into a single dataframe.
    """
    client = bigquery.Client(project)
 
    dataframe = (
        client.query(query_str)
        .result()
        .to_dataframe(
        create_bqstorage_client=True,
        )
    )
    return dataframe

In [5]:
project = 'gcp-ent-capstone-dev'
query_str = """
SELECT * 
FROM `gcp-ent-capstone-dev.TestTeam4.d_date_workdays`
"""

df = main(project, query_str)
df

,dt_id,mo_beg_dt,full_dt,workdays_in_mo,workday_of_mo,pct_workday_complete,qtr_beg_dt,workday_of_qtr,workdays_in_qtr,pct_qtr_workday_complete,semi_beg_dt,workday_of_semi,workdays_in_semi,pct_semi_workday_complete,yr_beg_dt,workday_of_yr,workdays_in_yr,pct_yr_workday_complete
0,20180101,2018-01-01,2018-01-01,22,0,0.000,2018-01-01,0,64,0.000,2018-01-01,0,128,0.000,2018-01-01,0,253,0.000
1,20180102,2018-01-01,2018-01-02,22,1,0.046,2018-01-01,1,64,0.016,2018-01-01,1,128,0.008,2018-01-01,1,253,0.004
2,20180103,2018-01-01,2018-01-03,22,2,0.091,2018-01-01,2,64,0.031,2018-01-01,2,128,0.016,2018-01-01,2,253,0.008
3,20180104,2018-01-01,2018-01-04,22,3,0.136,2018-01-01,3,64,0.047,2018-01-01,3,128,0.023,2018-01-01,3,253,0.012
4,20180105,2018-01-01,2018-01-05,22,4,0.182,2018-01-01,4,64,0.062,2018-01-01,4,128,0.031,2018-01-01,4,253,0.016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1821,20221227,2022-12-01,2022-12-27,20,17,0.850,2022-10-01,58,61,0.951,2021-07-01,122,125,0.976,2022-01-01,249,252,0.988
1822,20221228,2022-12-01,2022-12-28,20,18,0.900,2022-10-01,59,61,0.967,2021-07-01,123,125,0.984,2022-01-01,250,252,0.992
1823,20221229,2022-12-01,2022-12-29,20,19,0.950,2022-10-01,60,61,0.984,2021-07-01,124,125,0.992,2022-01-01,251,252,0.996
1824,20221230,2022-12-01,2022-12-30,20,20,1.000,2022-10-01,61,61,1.000,2021-07-01,125,125,1.000,2022-01-01,252,252,1.000
1825,20221231,2022-12-01,2022-12-31,20,20,1.000,2022-10-01,61,61,1.000,2021-07-01,125,125,1.000,2022-01-01,252,252,1.000

In [8]:
df.to_gbq('TestTeam4.d_date_workdays_test2', 'gcp-ent-capstone-dev', 'us-east1', if_exists = 'replace')

100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 1/1 [00:00<00:00, 4068.19it/s]